services:
  app:
    container_name: football-app
    build:
      context: .
      dockerfile: Dockerfile
    image: football
    ports:
      - "8015:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - football-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: football-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: football-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3315:3306"
    networks:
      - football-network

networks:
  football-network:

volumes:
  mysql-data:
